### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by andrkaz** [binsentsu/am43-ctrl#23]
sudo ./am43ctrl
/home/andkaz/node_modules/am43-ctrl/src/am43.js:29
    static busyDevice = null;
                      ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/andkaz/node_modules/am43-ctrl/index.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by willemdej** [comment]
do you installed as root?

**Comment by willemdej** [comment]
run and install in root map then > example; /am43ctrl 02b62c22d6bc -d --url mqtt://yourbrokerip:1883 -u username -p password

**Comment by andrkaz** [comment]
This problem solved. First I upgrade node.js to last version v14.15.1, after that am43ctrl can start manually. If try to start as service via systemd, some erorrs appear and service failed to start. I make sh script:

#!/bin/bash
sleep 60s
sudo /home/pi/node_modules/.bin/am43ctrl MAC --url mqtt://192.168.1.99 -u user -p pass -d

The "sleep" command is needed so that the other services have time to start. And finally put this script into crontab for start once when system is booting, like this:

@reboot root    /home/pi/am43.sh
