### ISSUE TITLE
Can't start (unexpected token)

### ISSUE THREAD

**Issue by danergo** [binsentsu/am43-ctrl#36]
```
# ./am43ctrl MYMAC -l 3000

/home/user/node_modules/am43-ctrl/src/am43.js:29
    static busyDevice = null;
                      ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/user/node_modules/am43-ctrl/index.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

```

I have followed the instructions, and no errors were found during the installation.
What am I doing wrong? Or this software is obsolete now?

Thank you!

**Comment by tomec-martin** [comment]
"Support for instance class fields starts with node >= 12"
Seems that nodejs 10 is not supported...
